### ISSUE TITLE
Preserve case

### ISSUE THREAD

**Issue by philippotto** [philippotto/Sublime-MultiEditUtils#13]
Consider this code:

```javascript
function computeFancyStuff() {
  var fancyStuff = ...
  const FANCYSTUFF
}
```

When multi-selecting all occurences (case-insensitive) of "fancyStuff" it is cumbersome to change it to "awesomeStuff"/"AwesomeStuff"/"AWESOMESTUFF", because the the case is not uniform.

I'm thinking how this could be simplified. Maybe one could activate a "preserve case" mode which keeps the case when characters are replaced or added? One could determine the "case type" of each selection before the first modification.

Possible case types could be:
- lower case
- UPPER CASE
- PascalCase
- camelCase
- snake_case
- dash-case

A special case would be when trying to change the case type while being in the "preserve case" mode. I'm not sure yet if this could/should be possible.

I'm going to prototype something to see if this could work out. Other thoughts and ideas are welcome :)

**Comment by timkrins** [comment]
Hi there,

I have been wanting an addon that does this for so long now, and I actually didn't find this issue till after I had written my own plugin!

You can see my plugin behavior here:
https://github.com/timkrins/Sublime-MultiLineCasePreserveEdit

I went for no-keyboard-shortcut editing but obviously this would conflict pretty heavily with just about every other plugin and screws up the undo buffer.

I am a straight-up beginner when it comes to writing plugins, and my plugin only just works albeit terribly - so I would probably use your feature when it gets merged into master (I won't submit my own dodgy plugin to Package Control)

Cheers,

**Comment by philippotto** [comment]
Hi @timkrins,

I'm sorry to hear that you did the work "in vain" :( I somehow forgot about this feature, but I'm happy that somebody else is interested in this. I just added the last refinements and merged it into the master. The new version is 1.6.0 and should be updated by your ST instance very soon.

Feel free to suggest improvements for the workflow of this feature.

Cheers!
