### ISSUE TITLE
Quick Find All for multiple selections is slow compare to quick find all.

### ISSUE THREAD

**Issue by eorroe** [philippotto/Sublime-MultiEditUtils#16]
I've realize that both **Quick Find All for multiple selections** and default **quick find all** are not the same, yet if I try to use your method `ctrl+alt+f` for the same thing that the default **quick find all** would do. It's relatively slow compare to the default one.

**Comment by philippotto** [comment]
You are absolutely right. The collection of regions was mutated while iterating over it which is obviously not a good idea :) I just didn't notice the issue because I don't use this feature.
But I fixed it now and the new version 1.6.3 should be speedy! Thanks for opening this issue!

**Comment by eorroe** [comment]
Yup just checked. It's fast thanks.
