### ISSUE TITLE
Auto populate and select replacement text for 'Preserve case while editing selection contents'

### ISSUE THREAD

**Issue by kruncher** [philippotto/Sublime-MultiEditUtils#19]
It would be super useful if the input field that appears for this feature was populated with the text of one of the input regions (fully selected) so that it is possible to make a single alteration to the string without having to type out the whole thing.

Is there such a feature or is it possible to add such a feature?

**Comment by philippotto** [comment]
My apologies for the late reply! This is a great suggestion and I'm going to implement it. Thanks!

**Comment by philippotto** [comment]
I just released a new version including your suggested feature. Sorry again, that it took so long.

**Comment by kruncher** [comment]
Awesome! thanks :D

**Comment by eorroe** [comment]
I'm confused on how to use this feature?
