### ISSUE TITLE
not a real issue

### ISSUE THREAD

**Issue by dawncold** [philippotto/Sublime-MultiEditUtils#20]
I'm sorry for posting an issue here, because I can't find your email on github.

I also got a problem like you, [https://github.com/babel/babelify/issues/64](https://github.com/babel/babelify/issues/64)

Have you ever any idea about babelify after closed that issue?

**Comment by philippotto** [comment]
Sorry, this issue got lost in my inbox. Unfortunately, I cannot remember what the culprit was. I'd recommend to open a new issue with at the babelify repo. They will be probably more helpful than me ;)
