### ISSUE TITLE
would you make a same package for the atom pls!

### ISSUE THREAD

**Issue by luxueyan** [philippotto/Sublime-MultiEditUtils#23]
It is a very nice package ,but now i use atom for working! If it can work in atom ,it will be perfect

**Comment by philippotto** [comment]
I'm glad you like the package and want to use it with Atom, but at the moment I don't have the time to port it (and to be honest, I also don't have the motivation, since I don't use Atom).
If somebody wants to jump in, I'm happy to provide some pointers if necessary!
