### ISSUE TITLE
I made a keyboard shortcut cheatsheet (pdf)

### ISSUE THREAD

**Issue by AllanLRH** [philippotto/Sublime-MultiEditUtils#28]
I'm so bad at remembering the keyboard shortcuts, that I made this small table with the keyboard shortcuts:
![multieditutilscheatsheetmain](https://user-images.githubusercontent.com/2641327/27285539-57bd445c-54fd-11e7-867f-2e3a264c7d35.png)
[multiEditUtilsCheatsheetMain.pdf](https://github.com/philippotto/Sublime-MultiEditUtils/files/1084890/multiEditUtilsCheatsheetMain.pdf)

It's typeset in LaTeX, and the source code is here:
[multiEditUtilsCheatsheet.zip](https://github.com/philippotto/Sublime-MultiEditUtils/files/1084891/multiEditUtilsCheatsheet.zip)

**Comment by philippotto** [comment]
Thank you, Allan! I integrated your cheat sheet into the project's readme :)

**Comment by AllanLRH** [comment]
Would you mind making the cheat-sheet image in the readme into a link to the PDF version – or include the pdf-link in some other way?

The original intent was for the cheat sheet to be printable, and put next to the screen, until the keyboard shortcuts are stuck in your (muscle)memory :)

**Comment by philippotto** [comment]
Sure, done ;)
