### ISSUE TITLE
Create cursor at begin and end of selected region

### ISSUE THREAD

**Issue by GlassGruber** [philippotto/Sublime-MultiEditUtils#29]
Hey there!
First of all thank you really for this plugin, awesome is a understatement! ;)

I hope it's not a RTFM issue, but I'm trying to find a way to have cursor created at the begin and end of selected regions. See attached img

![screenshot 1](https://user-images.githubusercontent.com/1172428/29753858-57d00bec-8b7a-11e7-85a6-f7e79b00dd8b.png)

**Comment by r-stein** [comment]
I think this is a little bit uncommon and I don't think there is an easy way to do it with this package, but you can easily create you own plugin doing that (a *plugin* is a python *file* containing the code and a *package* is the *folder*, which bundles plugins, syntax definitions, or color schemes).
Just select *Tools > Developer > New Plugin...* and paste this:

```py
import sublime_plugin


class SplitSelectionStartEndCommand(sublime_plugin.TextCommand):
    def run(self, edit):
        view = self.view
        sels = list(view.sel())
        view.sel().clear()
        for sel in sels:
            view.sel().add(sel.a)
            view.sel().add(sel.b)
```

Then create a keybinding to call the command:

```js
    {
        "keys": ["ctrl+alt+e"],
        "command": "split_selection_start_end",
    },
```

**Comment by GlassGruber** [comment]
Oh wow thank you!

I'm a novice in python but the code is pretty straightforward, creating plugins on my own is not something I ever thought because I'm not very confident with the API documented. 
But I should definetely start looking at it :P

Thank you again for your answer and your time!

**Comment by philippotto** [comment]
@GlassGruber Thanks for the praise! May I ask in which specific scenario this is useful? As @r-stein pointed out, this is not a baked-in functionality. However, for what it's worth, as a workaround you could achieve the desired effect as follows:

- copy the current selection
- invoke "Split Selection"
- paste the clipboard and hit enter

However, this only works if you have one selected region and not multiple ones. Maybe that's enough for you and makes having an additional plugin (+ shortcut) unnecessary.
