### ISSUE TITLE
tab behaviour not working

### ISSUE THREAD

**Issue by Tim-at-AST** [philippotto/Sublime-MultiEditUtils#30]
I installed multieditutils and everything working fine except the tab key.  It produces a normal tab instead of moving through fields.  Super+alt+d works as an alternative (and is the default).  The settings file looks fine.

Am using Build 3126.

What sorts of things could I check to see what is causing the issue?

**Comment by r-stein** [comment]
I assume you have a tab-keybinding with a higher precedence. You can try to copy the tab key binding from the [MultiEditUtils keymap](https://github.com/philippotto/Sublime-MultiEditUtils/blob/master/Default%20(OSX).sublime-keymap#L39) to your User keymap, i.e. insert the following to your keymap:

```js
  { "keys": ["tab"], "command": "selection_fields",
    "args": {"mode": "smart"},
    "context":
    [
      { "key": "is_selection_field" },
      { "key": "selection_fields_tab_enabled" },
      // set the default precedence to be less than snippet fields
      { "key": "has_next_field", "operator": "equal", "operand": false },
      { "key": "auto_complete_visible", "operator": "equal", "operand": false }
    ]
},
```

**Comment by Tim-at-AST** [comment]
I have already tried this, but no help unfortunately.  I use tab for snippet expansion successfully.
any other ideas?

**Comment by r-stein** [comment]
You can try to move it to the bottom of the keybinding file. Otherwise open the ST console ``ctrl+` `` and write `sublime.log_commands(True)` and check which commands are executed.

**Comment by Tim-at-AST** [comment]
Moving it to the bottom worked.  YAY!

**Comment by philippotto** [comment]
I'm glad this could be resolved! Thanks @r-stein for providing help.
